config/routes.rb
Rails.application.routes.draw do

  root 'messages#index' ## root route (AKA "/") displays the message board main page

  get 'login' => 'sessions#new' ## This displays the log in page
  
  post 'sessions' => 'sessions#create' ## This "creates" a new session when user logs in (AKA login route)

  delete 'sessions' => 'sessions#destroy' ## This "deletes" an existing session when user logs out (AKA logout route)

  get 'registration' => 'users#new' ## This displays the registration page

  post 'users' => 'users#create' ## This creates a new user in the users table (User model)

  get 'users/:id' => 'users#show' ## This shows a particular user's profile, which is then available for updating and deleting. ":id" refers to user id

  patch 'users/:id' => 'users#update' ## This updates a user's info. ":id" refers to user id

  delete 'users/:id' => 'users#destroy' ## This routes to the method that deletes the user from the users table (User model). ":id" refers to user id

  post 'messages/sort' => 'messages#sort'

  get 'messages/:message_id' => 'messages#show' ## This shows a particular post. ":message_id" should only be post. Show not enabled for comments.

  post "messages" => 'messages#create_post' ## This creates a new post (message with no parent)

  post 'messages/:parent_id' => 'messages#create_comment' ## This creates a new comment (message with parent. Parent can be post or comment)

  delete 'messages/:message_id/:post_id' => 'messages#destroy_comment', as: "destroy_comment" ## This deletes a particular message. Only the owner of message may delete.

  delete 'messages/:message_id' => 'messages#destroy' ## This deletes a particular message. Only the owner of message may delete.

  post 'likes/:message_id' => 'likes#create' ## This creates a new like. This is mapped to the "Like" button

  delete 'likes/:message_id' => 'likes#destroy' ## This deletes an existing like. This is mapped to the "Unlike" button

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :parent, class_name: "Message"
  
  has_many :likes
  has_many :users_liked, through: :likes, source: :user  ## people who liked this message
  has_many :comments, class_name: "Message", foreign_key: "parent_id", dependent: :destroy

  validates :content, presence: true
  validates :content, :length => { :maximum => 7, :tokenizer => lambda { |str| str.scan(/\w+/) }, :too_long  => "Please limit your summary to %{count} words" }, unless: :comment?
  validates :content, length: { in: 2..255 }, unless: :post?

  private

  def comment?
    parent_id != nil
  end

  def post?
    parent_id == nil
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_login, only: [:index, :create_post, :create_comment, :show, :destroy]
  # before_action :require_correct_user, only: [:destroy]


  # respond_to :html, :js
##################################################
  def index
	## root route (AKA "/") displays the message board main page
		## fetch all posts and put into @posts
		@posts = Message.where("parent_id is NULL").order("created_at DESC")

				
		@array_of_comments
		@comment_count_array = @posts.map { |post|
			@array_of_comments = []
			get_all_comments @array_of_comments, post.comments
			@array_of_comments.length
		}



  end

##################################################
  def sort
  	if params[:option] == "dropdown-recents"
			@posts = Message.where("parent_id is NULL").order("created_at DESC")
		elsif params[:option] == "dropdown-likesDESC"
			@posts = Message.select("messages.content, messages.parent_id, messages.user_id, messages.id, messages.created_at,count(likes.id) AS likes_count").joins("LEFT JOIN likes ON messages.id = likes.message_id").where("parent_id is NULL").group("messages.id").order("likes_count DESC")
		elsif params[:option] == "dropdown-oldest"
			@posts = Message.where("parent_id is NULL").order("created_at ASC")
		elsif params[:option] == "dropdown-likesASC"
			@posts = Message.select("messages.content, messages.parent_id, messages.user_id, messages.id, messages.created_at, count(likes.id) AS likes_count").joins("LEFT JOIN likes ON messages.id = likes.message_id").where("parent_id is NULL").group("messages.id").order("likes_count ASC")
		else params[:option] == ""
			@posts = Message.where("parent_id is NULL").order("created_at DESC")
		end
		@array_of_comments
		@comment_count_array = @posts.map { |post|
			@array_of_comments = []
			get_all_comments @array_of_comments, post.comments
			puts @array_of_comments.length
			@array_of_comments.length
		}
		puts "\n\n\n\n\n"
		print @comment_count_array

		@likes_count_array = @posts.map { |post|
			puts post.likes.count
			post.likes.count
		}
		puts "\n\n\n\n\n"
		print @likes_count_array
		
		render json: {posts: @posts, comments: @comment_count_array, likes: @likes_count_array}

  end


##################################################
  def show
	## This shows a particular post. ":message_id" should only be post. Show not enabled for comments.
  ## params[:message_id] should be available to it
  	@post = Message.find_by_id(params[:message_id])
  	if @post
	  	if @post.parent_id == nil
		  	@array_of_comments = []
		  	if @post.comments
		  		get_all_comments @array_of_comments, @post.comments.order("created_at DESC")
		  	end
		  else
		  	redirect_to "/"
		  end
		else
			redirect_to "/"
		end
  end


##################################################
  def create_post
	## This creates a new post (message with no parent)
		@post = Message.create(content: params[:content], user: current_user)
		
		if @post.valid?
      redirect_to "/", notice: "You have successfully created a dream!"
    else
      redirect_to :back, alert: @post.errors.full_messages
    end
  end


##################################################
  def create_comment
	## This creates a new comment (message with parent. Parent can be post or comment)
	## params[:parent_id] should be available to it
		@comment = Message.create(content: params[:content], user: current_user, parent_id: params[:parent_id])
		if @comment.valid?
			UserMailer.reply_email(@comment.parent.user, @comment.parent).deliver
      redirect_to "/messages/#{ params[:post_id] }", notice: "You have successfully created a comment!"
    else
      redirect_to "/messages/#{ params[:post_id] }", alert: @comment.errors.full_messages
    end
		
  end


##################################################
  def destroy
	## This deletes a particular message. Only the owner of message may delete.
		@message = Message.find(params[:message_id])
		if @message.user == current_user
			@message = Message.find(params[:message_id]).destroy
			if @message
				flash[:notice] = "You have successfully deleted your post!"
			else
				flash[:alert] = ["Could not delete post!"]
			end
		else
			flash[:alert] = ["Cannot delete someone else's post!"]
		end
		redirect_to "/users/#{current_user.id}"
  end
##################################################
  def destroy_comment
  ## This deletes a particular message. Only the owner of message may delete.
    @message = Message.find(params[:message_id])
    if @message.user == current_user
      @message = Message.find(params[:message_id]).destroy
      if @message
        flash[:notice] = "You have successfully deleted your comment!"
      else
        flash[:alert] = ["Could not delete comment!"]
      end
    else
      flash[:alert] = ["Cannot delete someone else's comment!"]
    end
    redirect_to "/messages/#{params[:post_id]}"
  end
##################################################
private
	def get_all_comments flattened_comments, commentList ## this is post.comments on the first run
		commentList.each do |comment|
			flattened_comments << comment
			if comment.comments
				get_all_comments(flattened_comments, comment.comments)
			end
		end
	end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_messages_table.html.erb
<h1>Hello world</h1>
<%= @posts %>

app/views/messages/index.html.erb
<div>
	<form action="/messages" method="post">
		<input type="hidden" name="authenticity_token" value = "<%= form_authenticity_token %>" >
			<h1 class="subject"><div class="col-md-5">What would you do if you: </div>
			<div class="col-md-4"><input class="dream-input form-control input-lg" type="text" name="content" size="20" placeholder="Enter your dream here"></div>
			<div class="col-md-1">?</div>
			<div class="col-md-2"><input type="submit" value="Post" class="btn btn-success btn-lg dream-post"></div></h1>
	</form>
</div>
<div class="col-md-9 col-md-offset-1">




	<div class="panel panel-primary">
	  <div class="panel-heading clearfix">
	    <h1 class="panel-title">Questions:
		    <div class="btn-group pull-right">
		  		<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Sort by <span class="caret"></span>
		  		</button>
		  		<ul class="dropdown-menu">
		  			<li><a href="/" id="dropdown-recents">Recent</a></li>
		  			<li><a href="/" id="dropdown-oldest">Oldest</a></li>
				    <li><a href="/" id="dropdown-likesDESC">Most Likes</a></li>
				    <li><a href="/" id="dropdown-likesASC">Least Likes</a></li>
		  		</ul>
		  		<!-- <form data-remote = "true" action = "/messages/sort" method = "post">
		  			<select>
		  				<option>Recent</option>
		  				<option>Recent</option>
		  				<option>Recent</option>
		  			</select>
		  			<input type = "submit" value = "click me">
		  		</form> -->
			</div>
	    </h1>
	  </div>


	  <div class="panel-body">
	  		<% @posts.each_with_index do |post, index| %>
			<h3><a href="/messages/<%= post.id %>">What would you do if you <span class="bold"><%= post.content %></span>?</a></h3>
			<p><%= post.likes.count %> likes / <%= @comment_count_array[index] %> comments / <%= post.created_at.strftime("%b %d, %Y %H:%M %p") %></p>	
		<% end %>
	  </div>
	</div>

</div>

app/views/messages/show.html.erb
	<h2>Dream</h2>
	<div class="well postWell">
		<div class="row">
			<div class="col-md-1 likes">
				<h4><%= @post.likes.count %> Likes</h4>
				<% if @post.users_liked.include? (current_user) %>
					<form action='/likes/<%= @post.id %>' method='post'>
				      <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
				      <input type='hidden' name='post_id' value='<%= @post.id %>' >
				      <input type='hidden' name='_method' value='delete'>
				      <input type='submit' value='Unlike' class="btn btn-warning unlike">
				    </form>
				<% else %>
					<form action='/likes/<%= @post.id %>' method='post'>
					  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
					  <input type='hidden' name='post_id' value='<%= @post.id %>' >
					  <input type='submit' value='Like' class="btn btn-info like">
					</form>
				<% end %>
			</div>
			<div class="col-md-10">
				<div class="row">
					<h3>
						<p><img class="avatar" src="<%=@post.user.avatar.url%>" alt="avatar_picture">
						<% unless @post.user.nickname =="" || @post.user.nickname == nil%>
							<%= @post.user.nickname %> asks:</p>
						<% else %>
							Anonymous asks:</p>
						<% end %>
					</h3>
					<p class="comment">What would you do if you <%= @post.content %>?</p>
				</div>
				<div class="row">
					<form action="/messages/<%= @post.id %>" method="post" class="replyBlock">
						<input type="hidden" name="authenticity_token" value = "<%= form_authenticity_token %>" >
						<input type="hidden" name="post_id" value="<%= @post.id %>" >
						<% unless @post.user.nickname == ""  || @post.user.nickname == nil %>
							<input type="text" name="content" value="@<%= @post.user.nickname %>: ">
						<% else %>
							<input type="text" name="content" value="@Anonymous: ">
						<% end %>
						<input type="submit" value="Reply" class="btn btn-success btn-sm reply" >
					</form>
					<p class="timestamp"><%= @post.created_at.strftime("%b %d, %Y %H:%M %p") %></p>

				</div>
			</div>

		</div>
	</div>

	<h2>Comments</h2>
		<%@array_of_comments.each do |comment| %>
			<div class="well commentWell">
				<div class="row">
					<div class="col-md-1 likes">
						<h4><%= comment.likes.count %> Likes</h4>
						<% if comment.users_liked.include? (current_user) %>
							<form action='/likes/<%= comment.id %>' method='post'>
						      <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
						      <input type='hidden' name='post_id' value='<%= @post.id %>' >
						      <input type='hidden' name='_method' value='delete'>
						      <input type='submit' value='Unlike' class="btn btn-warning unlike" >
						    </form>
						<% else %>
							<form action='/likes/<%= comment.id %>' method='post'>
							  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>
							  <input type='hidden' name='post_id' value='<%= @post.id %>' >
							  <input type='submit' value='Like ' class="btn btn-info like" >
							</form>
						<% end %>
					</div>
					<div class="col-md-10">
						<div class="row">
							<h3>
								<p><img class="avatar" src="<%=comment.user.avatar.url%>" alt="avatar_picture">
								<% unless comment.user.nickname == "" || comment.user.nickname == nil%>
									<%= comment.user.nickname %> says:</p>
								<% else %>
									Anonymous says:</p>
								<% end %>
							</h3>
							<p class="comment"><%= comment.content %></p>
						</div>
						<div class="row">
							<form action="/messages/<%= comment.id %>" method="post" class="replyBlock">
								<input type="hidden" name="authenticity_token" value = "<%= form_authenticity_token %>" >
								<input type="hidden" name="post_id" value="<%= @post.id %>" >
								<% unless comment.user.nickname == ""  || comment.user.nickname == nil%>
								<input type="text" name="content" value="@<%= comment.user.nickname %>: ">
								<% else %>
								<input type="text" name="content" value="@Anonymous: ">
								
								<% end %>
								<input type="submit" value="Reply" class="btn btn-success btn-sm replyBlock">
								<p><%= comment.created_at.strftime("%b %d, %Y %H:%M %p") %>
									<%= link_to "Delete", destroy_comment_path(comment, @post), method: :delete, data: {confirm: "Are you sure?"}, class: "red" %></p>
							</form>
						</div>
					</div>
				</div>
			</div>

		<% end %> 

app/views/messages/sort.js.erb
console.log("THis is being rendered");

$(".clearfix").html("<%= escape_javascript(render partial: "messages/messages_table") %>");